name: Run Beijing_Data.py every hour

on:
  schedule:
    - cron: '45 * * * *'
  push:
    branches: [main]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # 指定 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python Beijing_Data.py
        
#         working-directory: .  # 设置工作目录为根目录

      - name: Upload CSV
        uses: actions/upload-artifact@v2
        with:
          name: beijing-data
          path: ./data/气象数据*.csv
          
          
          
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2.13.0
        with:
          name: beijing-data
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: main.yml
          workflow_conclusion: completed,success
          repo: IMUT-SmallStudySlacker/BeijingMultiSiteAirQuality1.1
          path: ./data
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.9.16/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.16/x64/lib
          
          
      - name: List files in data directory
        run: ls data
        
        


        
        
        





